security:
  password_hashers:
    App\Entity\User: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: emailUser

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider

      user_checker: App\Security\UserChecker

      form_login:
        login_path: app_login
        check_path: app_login
        username_parameter: emailUser
        password_parameter: password

        # ✅ Redirection selon rôle (Admin -> Dashboard)
        success_handler: App\Security\LoginSuccessHandler

        # (Optionnel) si tu veux garder un fallback:
        # default_target_path: /home

      logout:
        path: app_logout
        target: /home

  role_hierarchy:
    ROLE_ADMIN: ROLE_MEDECIN
    ROLE_MEDECIN: ROLE_PATIENT
    ROLE_PATIENT: ROLE_USER

  access_control:
    - { path: ^/admin, roles: ROLE_STAFF }
    - { path: ^/ad, roles: ROLE_ADMIN }
    - { path: ^/staff, roles: ROLE_STAFF }
